# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQrjFXNWq-_eoA3C_gqeR3oti2qzcJru
"""

import pandas as pd

# Read Data From Google Drive
data = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/electricity consumption2.xlsx")

data.head()

data.tail()

data.sample(5)

data.shape

data.columns

data.dtypes

data.info()

data.describe(include="all")